# theme.toml template for a Hugo theme
# See https://github.com/gohugoio/hugoThemes#themetoml for an example

name = "Cuisine Book"
license = "MIT"
licenselink = "https://github.com/ntk148v/hugo-cuisine-book/blob/master/LICENSE"
description = ""
homepage = "https://github.com/ntk148v/hugo-cuisine-book"
tags = []
features = []
min_version = "0.41.0"

[author]
  name = "Kien Nguyen-Tuan"
  homepage = "https://github.com/ntk148v"

# If porting an existing theme
[original]
  name = "Jason Rametta"
  homepage = "https://github.com/rametta"
  repo = "https://github.com/rametta/recipe-book"
